//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothing_Season
    {
        public long Clothing_SeasonId { get; set; }
        public long Clothing_Id { get; set; }
        public long Season_Id { get; set; }
    
        public virtual Clothing Clothing { get; set; }
        public virtual Season Season { get; set; }
    }
}
