//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clothing()
        {
            this.Clothing_Season = new HashSet<Clothing_Season>();
            this.Clothing_Style = new HashSet<Clothing_Style>();
            this.Look_Clothing = new HashSet<Look_Clothing>();
        }
    
        public long ClothingId { get; set; }
        public long User_Id { get; set; }
        public long Cat_Id { get; set; }
        public string ImageLink { get; set; }
        public string Pattern { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string season { get; set; }
        public string style { get; set; }
        public string Favorite { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothing_Season> Clothing_Season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothing_Style> Clothing_Style { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Look_Clothing> Look_Clothing { get; set; }
    }
}
