//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClothinkDBEntities : DbContext
    {
        public ClothinkDBEntities()
            : base("name=ClothinkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Model> Category_Model { get; set; }
        public virtual DbSet<Clothing> Clothings { get; set; }
        public virtual DbSet<Clothing_Season> Clothing_Season { get; set; }
        public virtual DbSet<Clothing_Style> Clothing_Style { get; set; }
        public virtual DbSet<Look_Clothing> Look_Clothing { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<Style_Type> Style_Type { get; set; }
        public virtual DbSet<Look> Looks { get; set; }
    }
}
