//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Look_Clothing
    {
        public long Look_ClothingId { get; set; }
        public long Look_Id { get; set; }
        public long Clothing_Id { get; set; }
        public string LikeOrNot { get; set; }
    
        public virtual Clothing Clothing { get; set; }
        public virtual Look Look { get; set; }
    }
}
