//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Look
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Look()
        {
            this.Look_Clothing = new HashSet<Look_Clothing>();
        }
    
        public long LookId { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> LikeOrNot { get; set; }
        public bool Wore { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Look_Clothing> Look_Clothing { get; set; }
    }
}
